name: Junhyuck Woo
author: Junhyuck Woo
baseurl: 
description: theme for jekyll
github: http://www.github.com/Junhyuck-Woo
linkedin: http://www.linkedin.com/JunhyuckWoo
#twitter: http://www.twitter.com/
#facebook: http://www.facebook.com
linkedin: http://www.linkedin.com/JunhyuckWoo
email: junhyuck.woo+blog[at]gmail.com
location: Seoul, Republic of Korea
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
